config/routes.rb
Rails.application.routes.draw do

  mount Admin::Engine, :at => '/admin'

  get 'newsletter', to: 'pages#newsletter', as: 'newsletter'
  get 'extras', to: 'pages#extras', as: 'extras'
  get 'dictionary', to: 'pages#dictionary', as: 'dictionary'
  get 'i_hume_you', to: 'pages#i_hume_you', as: 'i_hume_you'
  get 'test/:level/:number', to: 'pages#test', as: 'test'
  get 'contact', to: 'pages#contact', as: 'contact'
  post 'contact', :to => 'pages#send_contact'
  get 'shop', to: 'purchases#shop', as: 'shop'
  post 'result' => 'achievements#results'
  get 'achievements' => 'achievements#index'

  devise_for :users

  root 'dashboard#index'
  get 'dashboard' => 'dashboard#index'

  resources :chapters do
    resources :supports, only: [:show]

    resources :contents do
      resources :supports, only: [:show]
    end
  end

  resources :supports, except: :all do
    resources :achievements, only: [:create]
  end

  # Problème au niveau des routes avec index, show et create -> Workaround avec index qui accessible via history_path
  post 'purchases', :to => 'purchases#create'
  scope :users do
    get 'history', :to => 'purchases#index'
    resources :purchases, only: [:show]
  end



  resources :students

  resources :groups do
    resources :students
  end

  resources :organisations, only: [:show] do
    resources :managers, exept: [:index]
  end

  devise_scope :user do
    # Route for create a private user
    post 'private_registration', :to => 'users/registrations#private_registration'
  end

  match '/403', :to => 'pages#forbidden', :as => 'forbidden', :via => :all
  match '/404', :to => 'pages#not_found', :as => 'not_found', :via => :all
  match '/500', :to => 'pages#internal_error', :as => 'internal_error', :via => :all

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @chapters = Chapter.get_all(current_user)
    @setting = Setting.find(1)
  end

end

app/views/dashboard/index.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">

		<span class="prefix-title">CAMPUS</span>
		<h1>WELCOME, <b><%= current_user.first_name.upcase %></b></h1>

		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<p><%= @setting.description %></p>
        <div class="row">
          <div class="col-md-12">
            <div class="panel with-nav-tabs panel-default">
              <div class="panel-heading">
                <ul class="nav nav-tabs">
                  <li class="active"><a href="#english" data-toggle="tab">English</a></li>
                  <li><a href="#german" data-toggle="tab">German</a></li>
                  <li><a href="#french" data-toggle="tab">French</a></li>
                  <li><a href="#spanish" data-toggle="tab">Spanish</a></li>
                  <li><a href="#italian" data-toggle="tab">Italian</a></li>
                  <li><a href="#portuguese" data-toggle="tab">Portuguese</a></li>
                  <li><a href="#arabic" data-toggle="tab">Arabic</a></li>
                  <li><a href="#chinese" data-toggle="tab">Chinese</a></li>
                </ul>
              </div>
              <div class="panel-body">
                <div class="tab-content">
                  <div class="tab-pane fade in active" id="english"><%= video_tag '/HOW_TO_USE/EN/movie.mp4', :controls => true, :autobuffer => true ,:class => 'support_video' %></div>
                  <div class="tab-pane fade" id="german"><%= video_tag '/HOW_TO_USE/DE/movie.mp4', :controls => true, :autobuffer => true ,:class => 'support_video' %></div>
                  <div class="tab-pane fade" id="french"><%= video_tag '/HOW_TO_USE/FR/movie.mp4', :controls => true, :autobuffer => true ,:class => 'support_video' %></div>
                  <div class="tab-pane fade" id="spanish"><%= video_tag '/HOW_TO_USE/ES/movie.mp4', :controls => true, :autobuffer => true ,:class => 'support_video' %></div>
                  <div class="tab-pane fade" id="italian"><%= video_tag '/HOW_TO_USE/IT/movie.mp4', :controls => true, :autobuffer => true ,:class => 'support_video' %></div>
                  <div class="tab-pane fade" id="portuguese"><%= video_tag '/HOW_TO_USE/PT/movie.mp4', :controls => true, :autobuffer => true ,:class => 'support_video' %></div>
                  <div class="tab-pane fade" id="arabic"><%= video_tag '/HOW_TO_USE/AR/movie.mp4', :controls => true, :autobuffer => true ,:class => 'support_video' %></div>
                  <div class="tab-pane fade" id="chinese"><%= video_tag '/HOW_TO_USE/CN/movie.mp4', :controls => true, :autobuffer => true ,:class => 'support_video' %></div>
                </div>
              </div>
            </div>

          </div>
        </div>
			</div>
		</div>

		<h2>YOUR COURSES</h2>
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<% if current_user.active_purchase? %>

					<!-- Available chapter -->
					<% @chapters.where(:release_date => nil).each do |chapter| %>
						<div class="col-md-4 col-sm-4 col-xs-6  padding-box <%= (current_user.type == 'Student' || current_user.type == 'Private' ? 'support_badge' : '') + " " + chapter.degree_achievement(current_user) %>" data-badge="<%= (current_user.type == 'Student' || current_user.type == 'Private' ? chapter.test(current_user).round.to_s + '%' : '') %>">
							<div class="box">
								<div class="image-content">
									<a href="<%= chapter_path(chapter) %>">
										<div class="box-hover">
											<div>Click to learn</div>
										</div>
									</a>
									<%= image_tag(chapter.thumbnail, :alt => chapter.name, :class => "img-responsive") %>
								</div>
							</div>
						</div>
					<% end %>
					<!-- END - Available chapter -->

					<!-- Comming soon -->
					<% @chapters.where.not(:release_date => nil).each do |chapter| %>
						<div class="col-md-4 col-sm-4 col-xs-6 padding-box">
							<div class="box">
								<div class="image-content">
									<div class="coming_soon">
									<span><big>Coming soon</big> </br>
										<%= chapter.release_date.strftime('%B %Y') %>   </span>
									</div>
								</div>
								<%= image_tag(chapter.thumbnail, :alt => chapter.name, :class => "img-responsive") %>
							</div>
						</div>
					<% end %>
					<!-- END - Comming soon -->

				<% else %>
					<% if current_user.type == 'Private' %>
						<em>
							Your trial period is over<br/>
							Help us to help you and <%= link_to 'sign up', shop_path %> for 6 months for only $29.90<br/>
							New content every month!
						</em>
					<% else %>
						<em>No content available</em>
					<% end %>
				<% end %>
			</div>
		</div>

		<% if current_user.type == 'Student' %>

			<h2>YOUR CLASS</h2>
			<div class="row">
				<div class="col-md-10 col-md-offset-1">
					<p><%= current_user.group.description %></p>
				</div>
			</div>

			<h2>YOUR PROFILE</h2>
			<div class="row">
				<div class="col-sm-6 col-md-3">
					<img src="http://placehold.it/200x250" alt="" class="img-responsive"/>
				</div>
				<div class="col-sm-6 col-md-9">
					<p><%= current_user.description %></p>
				</div>
			</div>

		<% end %>

	</div>
</div>
</div>