config/routes.rb
Rails.application.routes.draw do

  mount Admin::Engine, :at => '/admin'

  get 'newsletter', to: 'pages#newsletter', as: 'newsletter'
  get 'extras', to: 'pages#extras', as: 'extras'
  get 'dictionary', to: 'pages#dictionary', as: 'dictionary'
  get 'i_hume_you', to: 'pages#i_hume_you', as: 'i_hume_you'
  get 'test/:level/:number', to: 'pages#test', as: 'test'
  get 'contact', to: 'pages#contact', as: 'contact'
  post 'contact', :to => 'pages#send_contact'
  get 'shop', to: 'purchases#shop', as: 'shop'
  post 'result' => 'achievements#results'
  get 'achievements' => 'achievements#index'

  devise_for :users

  root 'dashboard#index'
  get 'dashboard' => 'dashboard#index'

  resources :chapters do
    resources :supports, only: [:show]

    resources :contents do
      resources :supports, only: [:show]
    end
  end

  resources :supports, except: :all do
    resources :achievements, only: [:create]
  end

  # Problème au niveau des routes avec index, show et create -> Workaround avec index qui accessible via history_path
  post 'purchases', :to => 'purchases#create'
  scope :users do
    get 'history', :to => 'purchases#index'
    resources :purchases, only: [:show]
  end



  resources :students

  resources :groups do
    resources :students
  end

  resources :organisations, only: [:show] do
    resources :managers, exept: [:index]
  end

  devise_scope :user do
    # Route for create a private user
    post 'private_registration', :to => 'users/registrations#private_registration'
  end

  match '/403', :to => 'pages#forbidden', :as => 'forbidden', :via => :all
  match '/404', :to => 'pages#not_found', :as => 'not_found', :via => :all
  match '/500', :to => 'pages#internal_error', :as => 'internal_error', :via => :all

end

app/models/content.rb
class Content < ActiveRecord::Base

  mount_uploader :thumbnail, ThumbnailUploader

  belongs_to :content_type
  belongs_to :chapter
  has_many :supports, as: :supportable
  has_many :accesses, as: :accessable

  validates :name, :content_type, presence: true

  def self.next_number(chapter)
    max = chapter.contents.all.maximum(:number)
    number ||= max ? max + 1 : 1
  end

  def support_path
    '/SUPPORT/' + self.chapter.number.to_s + '/'
  end

  # Renvoi si l'utilisateur a effectué le test ou non
  def test(user)
    if user.type == 'Student' || user.type == 'Private'
      self.supports.where('support_type_id = ? and (level = ? or level = 0)', SupportType.find_by_name("Quiz").id, user.level).first
    else
      nil
    end
  end
end

app/models/content_type.rb
class ContentType < ActiveRecord::Base

	has_many :contents
	has_many :packages

	validates :name, presence: true

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

  before_filter do |c|
    @chapter = Chapter.find(params[:chapter_id])
    add_breadcrumb "My course", chapters_path, :title => "Back to the Index"
    add_breadcrumb @chapter.name, chapter_path(@chapter), :title => "Back to the Index"
  end

  before_action :require_permission

  def show
    @content = Content.find(params[:id])
    @chapters = Chapter.get_all(current_user)
    @contents = Chapter.get_contents(current_user, @chapter)
    @supports = Chapter.get_supports(current_user, @chapter)

    add_breadcrumb @content.name, chapter_content_path(@chapter, @content), :title => "Back to the Index"
  end

  private

  def require_permission

    # Possède le chapitre
    if params[:chapter_id].present?
      chapter = Chapter.find(params[:chapter_id])
      chapters = Chapter.get_all(current_user)
      if !chapters.include?(chapter)
        return redirect_to forbidden_path
      end
    end

    # Possède le contenu
    if params[:id].present?
      content = Content.find(params[:id])
      chapter = Chapter.find(params[:chapter_id])
      contents = Chapter.get_contents(current_user, chapter)


      if !contents.include?(content)
        return redirect_to forbidden_path
      end
    end

  end

end

app/views/contents/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Your courses</h1>
    <hr>
  </div>
  <% @contents.each do |content| %>
  <div class="col-md-4 padding-box">
    <div class="box">
      <div class="image-content">

        <a href="<%= content_path(content) %>">
          <div class="box-hover">
            <h2>
              Click to learn
            </h2>
          </div>
        </a>

        <%= image_tag(content.thumbnail, :alt => content.name, :class => "img-responsive") %>

      </div>
      <div class="supports">
        <div class="row row-no-gutter">
          <% content.supports.each do |support| %>
            <div class="col-md-4">
              <a href="<%= content_support_path(content, support) %>"/>
                <div class="support <%= 'done' if support.support_type.name == 'Grammar' %>">
                  <i class="fa <%= support.support_type.icon %>" aria-hidden="true"></i>
                  <h1><%= support.support_type.name %></h1>
                </div>
              </a>
            </div>

          <% end %>

        </div>
      </div>
    </div>
  </div>

  <% end %>

</div>

app/views/contents/show.html.erb
<% content_for :sidebar do %>
    <%= render 'chapters/sidebar', chapters: @chapters, current_chapter: @chapter, current_content:@content, support: @supports  %>
<% end %>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <span class="prefix-title"><%= 'STEP ' + @content.chapter.number.to_s %></span>
    <h1>LESSON <b><%= @content.name.upcase %></b></h1>
  </div>
</div>

<div class="row">
  <div class="col-md-10 col-md-offset-1 col-sm-12">
    <% SupportCategory.all.each do |sc|  %>
      <h2>
        <%= sc.name.upcase %>
      </h2>
      <div class="row">

        <% @content.supports.where(support_category: sc, level: (current_user.type == "Student" ? [0, User.levels[current_user.level]] : [0..2])).each do |support| %>

          <div class="col-md-3 col-sm-6 col-xs-6 padding-box  <%= 'support_badge' + " " +support.degree_achievement(current_user) if support.support_type.name == "Quiz" %>" data-badge="<%= support.score_by_user(current_user).round %>% " >
            <div class="box">
              <div class="image-content support-item <%= support.degree_achievement(current_user) %>">

                <a href="<%= chapter_content_support_path(@chapter, @content, support) %>">
                  <div class="box-hover-support">
                    <div>Click to start</div>
                  </div>
                </a>

                <div class="support-cat">
                  <i class="fa <%= support.support_type.icon %> fa-3x" aria-hidden="true"></i>
                  <span class="text-cat">
                    <%= support.name %>
                  </span>
                </div>
              </div>
            </div>
          </div>

        <% end %>
      </div>
    <% end %>
  </div>
</div>