admin/config/routes.rb
Admin::Engine.routes.draw do

  root 'chapters#index'

  resources :settings

  resources :chapters do
    resources :supports, except: [:index]
    resources :contents
  end

  resources :contents do
    resources :supports, except: [:index]
  end

  resources :organisations do
    resources :managers, only: [:new, :create]
    resources :organizers, only: [:new, :create]
    resources :organisations_purchases, except: [:index, :destroy]
  end

  resources :privates do
    resources :privates_purchases, except: [:index, :destroy]
  end

  resources :purchases, only: [:index, :show]

  get "supports/change_order" => "supports#change_order", as: 'change_order_support'

end

admin/app/controllers/admin/organisations_controller.rb
module Admin
  class OrganisationsController < ApplicationController

    def index
      @organisations_grid = initialize_grid(Organisation)
    end

    def show
      @organisation = Organisation.find(params[:id])

      @nb_managers = @organisation.managers.count
      @nb_students = @organisation.students.count

      @managers_grid = initialize_grid(@organisation.users.where("type = 'Manager'"))
      @organizers_grid = initialize_grid(@organisation.users.where("type = 'Organizer'"))
      @purchases_grid = initialize_grid(@organisation.purchases)

    end

    def new
      @organisation = Organisation.new
    end

    def edit
      @organisation = Organisation.find(params[:id])
    end

    def create

      @organisation = Organisation.new(organisation_params)

      if @organisation.save
        flash[:success] = 'New organisation added successfully'
        redirect_to organisation_path(@organisation)
      else
        flash[:error] = 'Validation error'
        render 'new'
      end
    end

    def update

      @organisation = Organisation.find(params[:id])

      if @organisation.update(organisation_params)
        flash[:success] = 'Organisation updated successfully'
        redirect_to organisation_path(@organisation)
      else
        flash[:error] = 'Validation error'
        render 'edit'
      end

    end

    private

    def organisation_params
      params.require(:organisation).permit(:name, :nb_account_manager, :nb_account_student)
    end
  end
end

admin/app/views/admin/organisations/edit.html.erb
<h1>Edit Organisation</h1>

<%= form_for @organisation, html: {multipart: true, class: "form-horizontal"} do |f| %>

	<div class="form-group">
	    <div class="col-sm-2 text-right">
	    	<%= f.label :name, class: "control-label required" %>
	    </div>
	    <div class="col-sm-6">
	        <%= f.text_field :name, class: "form-control" %>
	        <span class="txtError"><%= @organisation.errors.get(:name).first %></span>
	    </div>
	</div>
	<div class="form-group">
	    <div class="col-sm-2 text-right">
	    	<%= f.label :nb_account_manager, class: "control-label required" %>
	    </div>
	    <div class="col-sm-6">
	        <%= f.number_field :nb_account_manager, class: "form-control" %>
	        <span class="txtError"><%= @organisation.errors.get(:nb_account_manager).first %></span>
	    </div>
	</div>
	<div class="form-group">
	    <div class="col-sm-2 text-right">
	    	<%= f.label :nb_account_student, class: "control-label required" %>
	    </div>
	    <div class="col-sm-6">
	        <%= f.number_field :nb_account_student, class: "form-control" %>
	        <span class="txtError"><%= @organisation.errors.get(:nb_account_student).first %></span>
	    </div>
	</div>

	
	  <div class="form-group">
	    <div class="col-sm-offset-2 col-sm-6">
	      <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-pencil"></i> Modify</button>
	    </div>
	  </div>

<% end %>

admin/app/views/admin/organisations/index.html.erb
<h1>List of Organisations</h1>

<a href="<%= new_organisation_path %>" class="btn btn-primary"><i class="fa fa-plus"></i> add organisation</a>
<br/><br/>

<%= grid(@organisations_grid) do |g|

  g.row_attributes do |organisation|
    {href: organisation_path(organisation)}
  end

  g.blank_slate  do
	   content_tag :div, "No organisation", class: 'well'
  end

  g.column name: 'ID' do |organisation|
    organisation.id
  end

  g.column name: 'Name' do |organisation|
    organisation.name
  end

  g.column name: 'Nunber manager account' do |organisation|
    organisation.nb_account_manager
  end

  g.column name: 'Nunber student account' do |organisation|
    organisation.nb_account_student
  end

end -%>

admin/app/views/admin/organisations/new.html.erb
<h1>Add Organisation</h1>

<%= form_for @organisation, html: {multipart: true, class: "form-horizontal"} do |f| %>

	<div class="form-group">
	    <div class="col-sm-2 text-right">
	    	<%= f.label :name, class: "control-label required" %>
	    </div>
	    <div class="col-sm-6">
	        <%= f.text_field :name, class: "form-control" %>
	        <span class="txtError"><%= @organisation.errors.get(:name).first %></span>
	    </div>
	</div>
	<div class="form-group">
	    <div class="col-sm-2 text-right">
	    	<%= f.label :nb_account_manager, class: "control-label required" %>
	    </div>
	    <div class="col-sm-6">
	        <%= f.number_field :nb_account_manager, class: "form-control" %>
	        <span class="txtError"><%= @organisation.errors.get(:nb_account_manager).first %></span>
	    </div>
	</div>
	<div class="form-group">
	    <div class="col-sm-2 text-right">
	    	<%= f.label :nb_account_student, class: "control-label required" %>
	    </div>
	    <div class="col-sm-6">
	        <%= f.number_field :nb_account_student, class: "form-control" %>
	        <span class="txtError"><%= @organisation.errors.get(:nb_account_student).first %></span>
	    </div>
	</div>

	
	  <div class="form-group">
	    <div class="col-sm-offset-2 col-sm-6">
	      <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-plus"></i> Add</button>
	    </div>
	  </div>

<% end %>

admin/app/views/admin/organisations/show.html.erb
<h1>
  <span>Organisation <%= @organisation.name %></span>
</h1>

<a href="<%= edit_organisation_path(@organisation) %>" class="btn btn-primary"><i class="fa fa-plus"></i> edit organisation</a>

<hr>

<dl class="dl-horizontal">
  <dt>Number of Manager</dt>
  <dd <%= 'class=full_account' if @nb_managers >= @organisation.nb_account_manager %>><%= @nb_managers %> / <%= @organisation.nb_account_manager %></dd>
  <dt>Number of Student</dt>
  <dd <%= 'class=full_account' if @nb_students >= @organisation.nb_account_student %>><%= @nb_students %> / <%= @organisation.nb_account_student %></dd>
</dl>

<h2>List of organizers</h2>

<a href="<%= new_organisation_organizer_path(@organisation) %>" class="btn btn-primary"><i class="fa fa-plus"></i> add organizer</a>
<br/><br/>

<%= grid(@organizers_grid) do |g|

  g.row_attributes do |purchase|
    {href: "#"}
  end

  g.blank_slate  do
     content_tag :div, "No organizer", class: 'well'
  end

  g.column name: 'ID' do |organizer|
    organizer.id
  end

  g.column name: 'First name' do |organizer|
    organizer.first_name
  end

  g.column name: 'Last name' do |organizer|
    organizer.last_name
  end

end -%>

<h2>List of managers</h2>

<a href="<%= new_organisation_manager_path(@organisation) %>" class="btn btn-primary" <%= 'disabled=disabled' if @nb_managers >= @organisation.nb_account_manager %>><i class="fa fa-plus"></i> add manager</a>
<br/><br/>

<%= grid(@managers_grid) do |g|

  g.row_attributes do |purchase|
    {href: "#"}
  end

  g.blank_slate  do
	   content_tag :div, "No manager", class: 'well'
  end

  g.column name: 'ID' do |manager|
    manager.id
  end

  g.column name: 'First name' do |manager|
    manager.first_name
  end

  g.column name: 'Last name' do |manager|
    manager.last_name
  end

end -%>

<h2>List of purchases</h2>

<a href="<%= new_organisation_organisations_purchase_path(@organisation) %>" class="btn btn-primary"><i class="fa fa-plus"></i> add purchase</a>
<br/><br/>

<%= grid(@purchases_grid) do |g|

  g.row_attributes do |purchase|
    {href: organisation_organisations_purchase_path(@organisation, purchase)}
  end

  g.blank_slate  do
   content_tag :div, "No purchase", class: 'well'
  end

  g.column name: 'ID' do |purchase|
    purchase.id
  end

  g.column name: 'Pruchase date' do |purchase|
    purchase.created_at.strftime("%d %b. %Y")
  end

  g.column name: 'Price' do |purchase|
    purchase.price
  end

  g.column name: 'From' do |purchase|
    purchase.from.strftime("%d %b. %Y")
  end

  g.column name: 'To' do |purchase|
    purchase.to.strftime("%d %b. %Y")
  end

  g.column name: 'Number of chapter' do |purchase|
    purchase.subscriptions.count
  end

end -%>