config/routes.rb
Rails.application.routes.draw do

  mount Admin::Engine, :at => '/admin'

  get 'newsletter', to: 'pages#newsletter', as: 'newsletter'
  get 'extras', to: 'pages#extras', as: 'extras'
  get 'dictionary', to: 'pages#dictionary', as: 'dictionary'
  get 'i_hume_you', to: 'pages#i_hume_you', as: 'i_hume_you'
  get 'test/:level/:number', to: 'pages#test', as: 'test'
  get 'contact', to: 'pages#contact', as: 'contact'
  post 'contact', :to => 'pages#send_contact'
  get 'shop', to: 'purchases#shop', as: 'shop'
  post 'result' => 'achievements#results'
  get 'achievements' => 'achievements#index'

  devise_for :users

  root 'dashboard#index'
  get 'dashboard' => 'dashboard#index'

  resources :chapters do
    resources :supports, only: [:show]

    resources :contents do
      resources :supports, only: [:show]
    end
  end

  resources :supports, except: :all do
    resources :achievements, only: [:create]
  end

  # Problème au niveau des routes avec index, show et create -> Workaround avec index qui accessible via history_path
  post 'purchases', :to => 'purchases#create'
  scope :users do
    get 'history', :to => 'purchases#index'
    resources :purchases, only: [:show]
  end



  resources :students

  resources :groups do
    resources :students
  end

  resources :organisations, only: [:show] do
    resources :managers, exept: [:index]
  end

  devise_scope :user do
    # Route for create a private user
    post 'private_registration', :to => 'users/registrations#private_registration'
  end

  match '/403', :to => 'pages#forbidden', :as => 'forbidden', :via => :all
  match '/404', :to => 'pages#not_found', :as => 'not_found', :via => :all
  match '/500', :to => 'pages#internal_error', :as => 'internal_error', :via => :all

end

app/models/group.rb
class Group < ActiveRecord::Base

  has_many :students
  belongs_to :manager

  has_many :accesses

  has_many :contents, :through => :accesses, :source => :accessable, :source_type => "Content"
  has_many :chapters, :through => :accesses, :source => :accessable, :source_type => "Chapter"

  validates :name, :presence => true

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_permission

  def index
    @groups_grid = initialize_grid(Group.where('manager_id = ?', current_user))
  end

  def show
    @group = Group.find(params[:id])
    @students_grid = initialize_grid(Student.where('group_id = ?', params[:id]))
    @chapters_grid = initialize_grid(Access.all_access_chapters(@group))

    add_breadcrumb @group.name, group_path(@group), :title => "Back to the Index"

  end

  def edit
    @group = Group.find(params[:id])
    @chapters = current_user.organisation.chapters

    add_breadcrumb @group.name, group_path(@group), :title => "Back to the Index"
    add_breadcrumb "Edit", edit_group_path(@group), :title => "Back to the Index"
  end

  def update
    @group = Group.find(params[:id])

    # Si aucun chapitre sélectionné, forcé le paramètre à vide (permet d'indiquer à ActiveRecord la modification)
    if params[:group][:chapter_ids].blank?
      params[:group][:chapter_ids] = [""]
    end

    # Si aucun contenu sélectionné, forcé le paramètre à vide (permet d'indiquer à ActiveRecord la modification)
    if params[:group][:content_ids].blank?
      params[:group][:content_ids] = [""]
    end

    if @group.update(group_params)
      flash[:success] = 'Content updated successfully'
      redirect_to group_path(@group)
    else
      @contents = Content.all
      @chapters = current_user.organisation.chapters
      flash[:error] = 'Validation error'
      render 'edit'
    end
  end

  def new
    @group = Group.new
    @chapters = current_user.organisation.chapters

    add_breadcrumb "New", new_group_path(@group), :title => "Back to the Index"
  end

  def create
    @group = Group.new(group_params)
    @group.manager_id = current_user.id

    if @group.save
      flash[:success] = 'New group added successfully'
      redirect_to group_path(@group)
    else
      @contents = Content.all
      @chapters = current_user.organisation.chapters
      flash[:error] = 'Validation error'
      render 'new'
    end
  end


private

  def group_params
    params.require(:group).permit(:name, :description, content_ids: [], chapter_ids: [])
  end

  def require_permission
    # Possède le rôle
    if current_user.type != 'Manager'
      return redirect_to forbidden_path
    end

    # Possède le groupe
    if params[:id].present?
      @group = Group.find(params[:id])
      if @group.manager != current_user
        return redirect_to forbidden_path
      end
    end
  end

end

app/views/groups/edit.html.erb
<span class="prefix-title">GROUP MANAGER</span>
<h1>EDIT GROUP</h1>

<%= form_for @group, html: {class: "form-horizontal"} do |f| %>

	<div class="form-group">
		<div class="col-md-1">
			<%= f.label :name, class: "control-label required" %>
		</div>
		<div class="col-sm-6">
			<%= f.text_field :name, class: "form-control" %>
			<span class="txtError"><%= @group.errors.get(:name).first %></span>
		</div>
	</div>

	<div class="form-group">
		<div class="col-md-1">
			<%= f.label :description, class: "control-label" %>
		</div>
		<div class="col-sm-6">
			<%= f.text_area :description, class: "form-control" %>
			<span class="txtError"><%= @group.errors.get(:description).first %></span>
		</div>
	</div>

	<h2>Manage content</h2>

	<% @chapters.each do |chapter| %>

		<% if chapter.release_date.blank? %>

			<h3>
				<div class="checkbox">
					<label>
						<%= check_box_tag 'group[chapter_ids][]', chapter.id, f.object.chapters.include?(chapter) %>
						<span class="cr"><i class="cr-icon glyphicon glyphicon-ok"></i></span>
						<%= chapter.name %> <span class="chapter-tools">Chapter tools</span>
					</label>
				</div>
			</h3>

			<div class="row well">

				<div class="col-md-12">
					<div class="checkbox">
						<label>
							<%= check_box_tag 'All access', 1, false, class: "chk_all_content_access", data: {"chapter" => chapter.id} %>
							<span class="cr"><i class="cr-icon glyphicon glyphicon-ok"></i></span>
							<i>Access all content</i>
						</label>
					</div>
				</div>
				<br/><br/>
				<% chapter.contents.each do |content| %>
					<div class="col-md-3">
						<h4>
							<div class="checkbox">
								<label>
									<%= check_box_tag 'group[content_ids][]', content.id, f.object.contents.include?(content), data: {"chapter" => chapter.id} %>
									<span class="cr"><i class="cr-icon glyphicon glyphicon-ok"></i></span>
									<%= content.name %>
								</label>
							</div>
						</h4>
					</div>
				<% end %>
			</div>

			<br/>
		<% end %>

	<% end %>

	<br/><br/>

	<div class="form-group">
		<div class="col-md-offset-1 col-md-6">
			<button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-plus"></i> Update</button>
		</div>
	</div>

<% end %>

app/views/groups/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="right">
      <a href="<%= new_group_path %>">
        <div class="update-nag">
          <div class="update-split"><i class="fa fa-plus"></i></div>
          <div class="update-text">New group</div>
        </div>
      </a>
    </div>
    <span class="prefix-title">GROUP MANAGER</span>
    <h1>LIST OF GROUPS</h1>
  </div>
</div>

<%= grid(@groups_grid) do |g|

  g.row_attributes do |group|
    {href: group_path(group)}
  end

  g.column name: 'Name' do |group|
    group.name
  end

  g.column name: 'Nb students' do |group|
    group.students.count
  end

  g.column name: 'Created at' do |group|
    group.created_at.strftime('%d.%m.%Y')
  end

end -%>

app/views/groups/new.html.erb
<span class="prefix-title">GROUP MANAGER</span>
<h1>ADD GROUP</h1>

<%= form_for @group, html: {class: "form-horizontal"} do |f| %>

	<div class="form-group">
		<div class="col-md-1">
			<%= f.label :name, class: "control-label required" %>
		</div>
		<div class="col-sm-6">
			<%= f.text_field :name, class: "form-control" %>
			<span class="txtError"><%= @group.errors.get(:name).first %></span>
		</div>
	</div>

	<div class="form-group">
		<div class="col-md-1">
			<%= f.label :description, class: "control-label" %>
		</div>
		<div class="col-sm-6">
			<%= f.text_area :description, class: "form-control" %>
			<span class="txtError"><%= @group.errors.get(:description).first %></span>
		</div>
	</div>

	<h2>Manage content</h2>

	<% @chapters.each do |chapter| %>

		<% if chapter.release_date.blank? %>

			<h3>
				<div class="checkbox">
					<label>
						<%= check_box_tag 'group[chapter_ids][]', chapter.id, f.object.chapters.include?(chapter) %>
						<span class="cr"><i class="cr-icon glyphicon glyphicon-ok"></i></span>
						<%= chapter.name %> <span class="chapter-tools">Chapter tools</span>
					</label>
				</div>
			</h3>

			<div class="row well">

				<div class="col-md-12">
					<div class="checkbox">
						<label>
							<%= check_box_tag 'All access', 1, false, class: "chk_all_content_access", data: {"chapter" => chapter.id} %>
							<span class="cr"><i class="cr-icon glyphicon glyphicon-ok"></i></span>
							<i>Access all content</i>
						</label>
					</div>
				</div>
				<br/><br/>
				<% chapter.contents.each do |content| %>
					<div class="col-md-3">
						<h4>
							<div class="checkbox">
								<label>
									<%= check_box_tag 'group[content_ids][]', content.id, f.object.contents.include?(content), data: {"chapter" => chapter.id} %>
									<span class="cr"><i class="cr-icon glyphicon glyphicon-ok"></i></span>
									<%= content.name %>
								</label>
							</div>
						</h4>
					</div>
				<% end %>
			</div>

			<br/>
		<% end %>

	<% end %>

	<br/><br/>

	<div class="form-group">
		<div class="col-md-offset-1 col-md-6">
			<button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-plus"></i> Add</button>
		</div>
	</div>

<% end %>

app/views/groups/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="right">
      <a href="<%= edit_group_path(params[:id]) %>" class="btn">
        <div class="update-nag">
          <div class="update-split"><i class="fa fa-cogs"></i></div>
          <div class="update-text">Manage group</div>
        </div>
      </a>
      <a href="<%= new_group_student_path(@group) %>" class="btn" <%= 'disabled=disabled' if current_user.organisation.nb_account_student <= current_user.organisation.students.count %>>
        <div class="update-nag">
          <div class="update-split"><i class="fa fa-user-plus"></i></div>
          <div class="update-text">Add student</div>
        </div>
      </a>
    </div>
    <span class="prefix-title">GROUP MANAGER</span>
    <h1>GROUP <b><%= @group.name %></b></h1>
    <p><%= @group.description %></p>
  </div>
</div>

<div class="row">
    <div class="col-md-12">
        <h2>List of Students</h2>
    </div>
</div>

<%= grid(@students_grid) do |g|

  g.row_attributes do |student|
    {href: group_student_path(@group.id, student)}
  end

  g.column name: 'First name' do |student|
  student.first_name
  end

  g.column name: 'Last name' do |student|
  student.last_name
  end

  g.column name: 'Email' do |student|
    student.email
  end

  g.column name: 'Created on' do |student|
  student.created_at.strftime('%d.%m.%Y')
  end

  g.column name: 'Account confirmed' do |student|
    student.invitation_accepted_at.blank? ?  raw("<span class='txt_red'>No</span>") : raw("<span class='txt_green'>Yes</span>")
  end

  g.column name: 'Progression' do |student|


    supports = []
    chapters = Access.all_access_chapters(student.group)
    chapters.each do |chapter|
      Access.contents_access(student.group, chapter).each do |content|
        supports.push( content.supports)
      end
    end

    achieved = Achievement.where(user_id: student.id).distinct.count()
    all_supports = Support.available(student).count()
    done = (achieved.to_f / all_supports.to_f * 100.0).round

    "#{achieved.to_s} / #{all_supports.to_s}".html_safe
  end

  g.column name: 'Score' do |student|
    sum_support = Achievement.where(user_id: student.id).distinct.sum(:score)
    sum_support = sum_support / Achievement.where(user_id: student.id).distinct.count()

    "<div class='progress' style='width:120px;'>
      <div class='progress-bar progress-bar-striped' role='progressbar' aria-valuenow='#{sum_support.to_s}' aria-valuemin='0' aria-valuemax='100' style='width: #{sum_support.to_s}%'>

       #{ sum_support.nan? ? 0 : sum_support.round} %
        </div>
      </div>".html_safe
  end


end -%>


<div class="row">
  <div class="col-md-12">
    <h2>Access management</h2>
  </div>
</div>

<%= grid(@chapters_grid) do |g|

  g.row_attributes do |student|
    {class: "no-link"}
  end

  g.column name: 'Steps' do |chapter|
    chapter.number
  end

  g.column name: 'Access' do |chapter|
    Access.access_to_chapter?(@group,chapter)
  end

  g.column name: 'Content' do |chapter|
    Access.contents_access(@group,chapter).map {|c| c.name }.join(", ")
  end

end -%>